[tool.poetry]
name = "dataset-ch-hon-flux-product"
version = "0.1.0"
description = "Flux data processing pipeline for the CH-HON forest station"
authors = ["Lukas Hörtnagl <lukas.hoertnagl@usys.ethz.ch>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pandas = "^2.0"
matplotlib = "^3.8"
numpy = "^1.24"
diive = { path = "../../21 - DIIVE/diive", develop = true }

[tool.poetry.group.dev.dependencies]
dbc-influxdb = { path = "../../22 - POET/dbc-influxdb", develop = true }
ghp-import = "^2.1.0"
jupyter-book = "^1.0.4.post1"
sphinxcontrib-mermaid = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
